# This file relates to internal XMOS infrastructure and should be ignored by external users
---
lib_name: lib_i2s
project: '{{lib_name}}'
title: '{{lib_name}}: IÂ²S/TDM library'
version: 6.0.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  root_doc: doc/rst/lib_i2s.rst
  linkcheck_ignore_regex: ['']
  cognidox_part_number: XM-007055-UG
  doxygen_projects:
    lib_i2s:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_i2s.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-007504-SM
